### ISSUE TITLE
"Import data from logs" does not work with *some* logs

### ISSUE THREAD

**Issue by csansoon** [latitude-dev/latitude-llm#238] opened 2024-09-20 08:02 UTC
https://github.com/user-attachments/assets/1a26c3b3-8904-48df-bc4e-8f38b05ec8e4

**Comment by geclos** [comment] 2024-09-20 08:12
:O any errors in console?

**Comment by csansoon** [comment] 2024-09-20 08:15
No errors, nope

**Comment by geclos** [comment] 2024-09-20 08:18
ok please share the offending log contents if you can so that we can reproduce it locally

**Comment by csansoon** [comment] 2024-09-20 08:25
![image](https://github.com/user-attachments/assets/6e2dbdce-abcc-4608-a385-92f3bcad159b)

This is one of the logs that fail importing.

Not sure if it's related, but this is one of the logs that was generated by "Run batch evaluation", where it generated logs but didn't create evaluation results. ((may not be related))

**Comment by csansoon** [comment] 2024-09-20 08:27
Oh, and the prompt, if it helps:

![image](https://github.com/user-attachments/assets/2dc0bc57-db2d-4dd3-b0ae-569084322620)

**Comment by geclos** [comment] 2024-09-24 19:52
closing couldn't reproduce

**Closed by geclos** 2024-09-24 19:52 UTC
Labels: bug, p1
